### ISSUE TITLE
incompatible with revel's 'betterprogression' mod. breaks ui, spawns inventory full of placeholder fork items. blocks ui interaction.

### ISSUE THREAD

**Issue by Chad90b** [BruceOfTheBow/ComfyArmorAndQuickSlots#13]
combo of two mods breaks the ui, spawns with inventory full of a random fork-like item, cannot craft; button blocked. clicking the crafting icon removes it...

not sure what to think, but there's some sort of bug or conflict here. between the two mods ComfyArmorAndQuickSlots (**ComfyQuickSlots**) which is your mod and **BetterProgression** which is made by revel but uploaded by someone unknown; i found no way to contact them.

BepInEx log output:
``[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
InventoryGrid.GetElement (System.Int32 x, System.Int32 y, System.Int32 width) (at <da52c09f594f4a7480000b7420815ba7>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <da52c09f594f4a7480000b7420815ba7>:0)
InventoryGui.UpdateInventory (Player player) (at <da52c09f594f4a7480000b7420815ba7>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)``

and here's what it looks like and the list of mods enabled during testing:

![image](https://github.com/BruceOfTheBow/ComfyArmorAndQuickSlots/assets/68355086/15c25608-bdae-478a-9eff-fa7a1ae3697a)
![image](https://github.com/BruceOfTheBow/ComfyArmorAndQuickSlots/assets/68355086/25fedb87-214e-4001-8a47-75e7c0450d8e)

**Comment by BruceOfTheBow** [comment]
I'm not planning to add compatibility for this mod at this time as this mod was made and is maintained mainly for the Comfy Valheim server which does not use BetterProgression
