### ISSUE TITLE
Conflict with Jewelcrafting (and Soulcatcher)

### ISSUE THREAD

**Issue by RoyAwesome** [BruceOfTheBow/ComfyArmorAndQuickSlots#3]
Heyoo

I have discovered a mod conflict with Comfy Quickslots and Jewelcrafting (which has a secondary effect with Soulcatcher).

https://valheim.thunderstore.io/package/Smoothbrain/Jewelcrafting/

If I try to craft a gem in Jewelcrafting's crafting table, and it fails, it spawns Gem Shards, which throws a warning in the console only when Quickslots is also running (and no issue when it's not):

`[Info   : Unity Log] 12/11/2022 13:23:44: Item missing prefab $jc_shattered_green_crystal`

This causes the shattered crystals to not save when going out of range of chests or when you log off with them in your inventory.  If Soulcatcher is installed, that mod throws an error due to the missing prefab.

I've spoken to the author of Jewelcrafting and he indicated that it was probably an issue with this mod, not jewelcrafting.

**Comment by BruceOfTheBow** [comment]
It looks like that warning is logged when an inventory item does not have an item.m_dropPrefab when Inventory.Save() is called. ComfyQuickSlots shouldn't be causing this error as it uses the vanilla Inventory.Save(ZPackage) method. I'd ask the jewelcrafting author to take another look.
