### ISSUE TITLE
Add IsQuickSlot as public static method for compatibility

### ISSUE THREAD

**Issue by Goldenrevolver** [BruceOfTheBow/ComfyArmorAndQuickSlots#5]
This isn't a bug, it would just make it easier for other mods to provide support for your mod.

We can check if a slot is an armor slot with IsArmorSlot, and we can kinda hack if a slot is an armor slot or a quick slot by additionally asking IsArmorSlot(new Vector2i(itemPos.x - 3, itemPos.y)) but that relies on your current index setup so it's not very safe.

It would be great if you could add a simple public static method IsQuickSlot that simply returns whether the vector is contained in an array of those 3 vectors even if you never use it in your own code (and maybe add a comment over both IsArmorSlot and IsQuickSlot to not rename or move them or put them in a separate class called API (please don't delete the current ComfyQuickSlots.IsArmorSlot immediately or at all to not break backwards compatibility immediately))

thank you for considering this change

**Comment by BruceOfTheBow** [comment]
Let me know if this works for you and I can update on TS. https://github.com/BruceOfTheBow/ComfyArmorAndQuickSlots/commit/9921b3e2fb3a0258d887973417a43e8c3825099f

**Comment by BruceOfTheBow** [comment]
In release.

**Comment by BruceOfTheBow** [comment]
In release.
